spring:
  application:
    name: gateway
server:
  port: 8080

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
    rating-service:
      path: /rating-service/**
      sensitive-headers: Set-Cookie,
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082

hystrix:
  command:
    book-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    rating-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000